# Exemplo de como poderia ser uma alternativa (verifique a documentação da ação escolhida)
name: Generate Snake (Alternative)

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar SVG da cobrinha (Usando Ação Alternativa)
        # Substitua esta linha pela ação alternativa que encontrar
        uses: Sutil/github-contribution-snake-action@v01.00.02 # Exemplo
        with:
          github_user_name: gabi-ulisses
          # Verifique as opções de saída da ação alternativa
          output: dist/github-contribution-grid-snake.svg

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
