name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

# Adicione o bloco de permissões aqui, no nível do workflow
permissions:
  contents: write # Permite que o GITHUB_TOKEN escreva no repositório
  pages: write    # Permite que o GITHUB_TOKEN gerencie o GitHub Pages
  id-token: write # Permite o uso de tokens OIDC, que podem ser usados por algumas ações

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Gerar SVG da cobrinha
        uses: Platane/snk/svg-only@v4
        with:
          github_user_name: gabi-ulisses
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
