name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *"  # Corrigido para rodar exatamente a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          github_user_name: gabi-ulisses
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
